# ─── Application ────────────────────────────────────────────
quarkus.application.name=ecommerce-api
quarkus.application.version=1.0.0
quarkus.http.port=8080

# ─── Database ───────────────────────────────────────────────
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=ecommerce
quarkus.datasource.password=ecommerce123
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5435/ecommerce_db

# ─── Hibernate ──────────────────────────────────────────────
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=false

# ─── OpenAPI / Swagger ──────────────────────────────────────
quarkus.smallrye-openapi.info-title=Ecommerce API
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.smallrye-openapi.info-description=REST API for e-commerce built with Quarkus and PostgreSQL
quarkus.smallrye-openapi.info-contact-name=Michael
quarkus.smallrye-openapi.info-contact-url=https://github.com/Michael-2405
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/q/swagger-ui

# ─── Profiles ───────────────────────────────────────────────
%dev.quarkus.hibernate-orm.log.sql=true
%prod.quarkus.hibernate-orm.database.generation=none
